#!/bin/bash
# Help dialogue.
if [[ $1 = "help" || $1 = "--help" || $1 = "-help" ]]; then
	echo Usage:
	echo wtfetch [export\|help]
	echo If export parameter is added, you can also set a folder name to dump the specs to. 
	echo Otherwise, the folder defaults to ./specs/
	echo If help parameter is added, show this dialogue
	exit 0
fi
# Extract DISTRO_ID value from /etc/something-release, e.g. /etc/arch-release for Arch
export DISTRO=$(cat /etc/*-release 2>/dev/null | grep -Po '(?<=DISTRIB_ID=")(.*)(?=")') 
# Extract the CPU name from lscpu, while removing extra symbols like (R) for registered trademarks.
export CPU=$(lscpu | grep -Po '(?<=Model name:).*(?=.*)' | sed -e 's/(\([Rr]\))//g') 
# This next line to get the frequency of the CPU needs a bit more explaining:
# First, we check the bios_limit file to try to get it there. 
# If that doesn't work, we try scaling_mex_freq in the same folder.
# If that also doesn't work, we try cpuinfo_max_freq in the same folder.
# If all of these fail, then we just output 0.
export CPUFREQHZ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/bios_limit 2>/dev/null || cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 2>/dev/null || cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq 2>/dev/null || echo 0)
# This formats the CPU frequency to MHz or GHz when appropriate.
export CPUFREQHZ_FORMATTED=$(echo $(echo $(awk -- 'BEGIN{printf "%.3f\n", ARGV[1]/ARGV[2]/(1000**ARGV[3])}' "$CPUFREQHZ" "1000" "$((CPUFREQHZ >= 1000000))" )) $([[ $CPUFREQHZ -ge 1000000 ]] && echo "GHz" || echo "MHz"))
# This gets the amount of memory in bytes from the free command.
export MEMORYTOTAL_BYTES=$(free -b | grep -Po 'Mem:[ ]*([0-9]+)' | grep -Po '([0-9]+)')
# This uses MEMORYTOTAL_BYTES and reformats it using numfmt.
export MEMORYTOTAL_FORMATTED=$(echo $MEMORYTOTAL_BYTES | numfmt --to=iec)
# This gets the used memory, also from the free command.
export MEMORYUSED_BYTES=$(free -b | grep -Po 'Mem:(( )*[0-9]+){1,2}' | grep -Po '[0-9]+$')
# Works the exact same as MEMORYTOTAL_FORMATTED.
export MEMORYUSED_FORMATTED=$(echo $MEMORYUSED_BYTES | numfmt --to=iec)
# Version of the kernel we're running.
export KERNEL_VERSION=$(uname -r)
# Get the usernamer of the user running the command.
export USERNAME=$(whoami)
# Get the hostname of the device from /etc/hostname.
export HOSTNAME=$(cat /etc/hostname)
# Get the shell name via $SHELL from the entire path (e.g. /usr/bin/zsh) and then get after the last "/" via the grep pattern.
export SHELL=$(echo $SHELL | grep -Po '[^\/]*$')
# Get the CPU architecture from uname.
export ARCH=$(uname -m)
# Get GPU model
if [[ $(lspci -k | grep -EA3 'VGA|3D|Display') == *"NVIDIA"* ]]; then
	export GPU=$(cat /proc/driver/nvidia/gpus/00*/information | grep -Po "(?<=Model\:)[ ]+(.*)")
elif [[ $(lspci -k | grep -EA3 'VGA|3D|Display') == *"AMD"* ]]; then
	export GPU=$(lspci -k -d ::03xx | grep -Pom1 "((\[|Subsytem: )?((RX|HD|Radeon) .*)(\])?)" | sed -e 's/\[//' -e 's/\]//')
fi
# Finally, print everything out.
echo Software:
echo ---------
echo OS:\ \ \ \ \ \|\-\> $DISTRO \(Linux\)
echo \ \ \ \ \ \ \ \ \|-\> Username: -\> $USERNAME
echo \ \ \ \ \ \ \ \ \|-\> Hostname: -\> $HOSTNAME
echo \ \ \ \ \ \ \ \ \|-\> Shell: -\> $SHELL
echo \ \ \ \ \ \ \ \ \\\-\> Kernel version\: -\> $KERNEL_VERSION
echo 
echo Hardware:
echo ---------
echo CPU:\ \ \ \ \|\-\> $CPU 
echo \ \ \ \ \ \ \ \ \|-\> Architecture: -\> $ARCH
echo \ \ \ \ \ \ \ \ \\-\> Frequency\: -\> $CPUFREQHZ_FORMATTED \($CPUFREQHZ Hz\)
echo
echo RAM:\ \ \ \ \|\-\> $MEMORYUSED_FORMATTED/$MEMORYTOTAL_FORMATTED \($MEMORYUSED_BYTES/$MEMORYTOTAL_BYTES B\)
echo
echo GPU:\ \ \ \ \|\-\> $GPU
# If the user wants all the more set-in-stone numbers (e.g. CPU frequency, but excluding used RAM) then they would add export (and then optionally a directory name). 
# Here, we check if they want that. If not, then this gets skipped
if [[ $1 == "export" ]]; then
	echo
	FOLDER=$2
	# By default, the folder name is specs/ unless specified. Assign that here when it's unspecified.	
	if [ -z "$FOLDER" ]; then
		FOLDER=specs
	fi
	echo Exporting to folder $FOLDER...
	# Make the folder 
	mkdir $FOLDER || echo Error making folder: ignored
	# Export it all out into files.
	# SOFTWARE:
	echo $DISTRO > ./$FOLDER/os
	echo $USERNAME >> ./$FOLDER/os
	echo $HOSTNAME >> ./$FOLDER/os
	echo $SHELL >> ./$FOLDER/os
	echo $KERNEL_VERSION >> ./$FOLDER/os
	# HARDWARE:
	# CPU specs
	echo $CPU > ./$FOLDER/cpu
	echo $ARCH >> ./$FOLDER/cpu
	echo $CPUFREQHZ >> ./$FOLDER/cpu
	echo $CPUFREQHZ_FORMATTED >> ./$FOLDER/cpu 
	# RAM specs
	echo $MEMORYTOTAL_BYTES > ./$FOLDER/mem
	echo $MEMORYTOTAL_FORMATTED >> ./$FOLDER/mem
	# GPU specs
	echo $GPU > ./$FOLDER/gpu
fi
